spring:
  datasource:
    url: jdbc:h2:mem:appsecboxmem
  flyway:
    enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  address: 192.168.56.5
  port: 9999

logging:
  level:
    ROOT: INFO
