spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appsecbox
    username: appsecboxuser
    password: password
  flyway:
    enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: false
  profiles:
    active: default

server:
  address: 192.168.56.5
  port: 9999

logging:
  level:
    ROOT: INFO
